steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - ui/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/lease-lens-repo/lease-lens-ui:$COMMIT_SHA
      - ui

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/lease-lens-repo/lease-lens-ui:$COMMIT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - lease-lens-ui
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/lease-lens-repo/lease-lens-ui:$COMMIT_SHA
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - GOOGLE_CLOUD_PROJECT=$PROJECT_ID

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/lease-lens-repo/lease-lens-ui:$COMMIT_SHA
